### ISSUE TITLE
Can not return an array from a method.

### ISSUE THREAD

**Issue by GUDwyo** [dinazil/she-codes-csharp-for-beginners#3]
static int[] ArraySquare(int[] array)
        {
            int[] squares = new int[array.Length];
            for (int i = 0; i < array.Length; ++i)
            {
                squares[i] = array[i] \* array[i];
            }
            return **squares**;
        }

I get an error message on **squares** telling me I can not implicitly convert int[] to int.

after doing some research it seems you can not return an array from a method.

**Comment by dinazil** [comment]
This code is actually fine and runs just OK on 
`int[] squares = ArraySquare(new[] {1, 2, 3, 4});`
Can you provide the entire file maybe? Can you share the link where it said you can't return arrays?
It's absolutely OK to return arrays from methods. For example, here are some standard functions that do that: [String.Split](https://msdn.microsoft.com/en-us/library/system.string.split%28v=vs.110%29.aspx), [Enumerable.ToArray](https://msdn.microsoft.com/library/bb298736%28v=vs.100%29.aspx), [Process.GetProcesses](https://msdn.microsoft.com/en-us/library/1f3ys1f9%28v=vs.110%29.aspx), and many more...

**Comment by GUDwyo** [comment]
I figured out the problem shortly after opening this. I wanted to delete my entry but I don't see how.

**Comment by dinazil** [comment]
I was just afraid that what you figured out was that it just was impossible and gave up...
